defmodule TermUI.Property.EscapeParserTest do
  use ExUnit.Case, async: true

  alias TermUI.Event
  alias TermUI.Terminal.EscapeParser
  alias TermUI.Test.BoundaryCases, as: Cases

  test "valid terminal tokens have the same events at every generated byte boundary" do
    Cases.check(&terminal_input/0, fn {input, chunks} ->
      {whole, whole_remaining} = EscapeParser.parse(input)

      {split, split_remaining} =
        Enum.reduce(chunks, {[], ""}, fn chunk, {events, remaining} ->
          {next, remaining} = EscapeParser.parse(remaining <> chunk)
          {events ++ next, remaining}
        end)

      assert normalize(split) == normalize(whole)
      assert split_remaining == whole_remaining
      assert whole_remaining == ""
    end)
  end

  test "bounded arbitrary bytes do not crash and leave only a suffix for later input" do
    Cases.check(&Cases.bytes/0, fn input ->
      {events, remaining} = EscapeParser.parse(input)
      assert byte_size(remaining) <= byte_size(input)

      assert binary_part(input, byte_size(input) - byte_size(remaining), byte_size(remaining)) ==
               remaining

      assert length(events) <= byte_size(input)
      assert Enum.all?(events, &match?({:ok, _event}, Zoi.parse(Event.schema(), &1)))
      assert normalize(elem(EscapeParser.parse(input), 0)) == normalize(events)
    end)
  end

  defp terminal_input do
    tokens = [
      "a",
      "é",
      "界",
      "👩‍💻",
      "\t",
      "\r",
      "\e[A",
      "\e[1;5D",
      "\e[Z",
      "\eOP",
      "\e\x7f",
      "\e[200~one\ntwo\e[201~",
      "\e[?25l"
    ]

    input = for _index <- 1..Cases.integer(1, 12), into: "", do: Cases.choose(tokens)
    {input, Cases.chunks(input)}
  end

  defp normalize(events), do: Enum.map(events, &Map.delete(&1, :timestamp))
end
